name: perdimeupet
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  google_sign_in: ^5.4.1
  font_awesome_flutter: ^10.1.0
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  image_picker: ^0.8.5+3
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+1
  calendar_date_picker2: ^0.2.2
  kmeans: ^1.0.0
  firebase_storage: ^10.3.8
  firebase_core: ^1.22.0
  dio: ^4.0.6
  connectivity_plus: ^2.3.7
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.6
  mask_text_input_formatter: ^2.4.0
  salomon_bottom_bar: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.4
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
      - assets/images/main-img.png
      - assets/images/sign-in.png
      - assets/images/logo.png
      - assets/images/
      - assets/cat.png
      - assets/dog.png  
      - assets/gatos/1.png
      - assets/gatos/2.png
      - assets/gatos/3.png
      - assets/gatos/4.png 
      - assets/encontrado.png
      - assets/devolvido.png
      - assets/back.jpg
      - assets/logo_perdi.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 100
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 700 
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 700